version: '3'
services:
  php-fpm:
    build: ./docker/php/
    volumes:
     - .:/var/www/html
  nginx:
    image: nginx
    volumes:
     - ./docker/ngingx/mimimibot.template:/etc/nginx/conf.d/mysite.template
    ports:
     - 8080:80
     - 443:443
    environment:
     - NGINX_HOST=mimimiSlackBot.com
     - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
