version: '3'

services:
  nginx:
    build: ./docker/nginx
    depends_on:
      - fpm
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/app
      - ./var/logs/nginx:/var/log/nginx

  fpm:
    build: ./docker/fpm
    environment:
      - PHP_IDE_CONFIG=serverName=mimimi-slack-bot
    ports:
      - 9000:9000
    volumes:
      - .:/app
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - /etc/ssl:/etc/ssl
