version: '3'

services:

  php-fpm-nginx:
    image: richarvey/nginx-php-fpm:latest
    ports:
      - 8080:80
      - 443:443
      - 9000:9000
    volumes:
      - .:/var/www/html/
      - ./var/nginx:/var/log/nginx
    environment:
      - WEBROOT=/var/www/html/public
      - ENABLE_XDEBUG=1
      - XDEBUG_CONFIG=remote_host=10.64.0.66
      - PHP_IDE_CONFIG=serverName=XdebugPhpStormServerConfig
